
export const DICT = {
  en: {
    trails: "Trails",
    details: "Details",
    map: "Map",
    downloads: "Downloads",
    profile: "Profile",
    searchTrails: "Search trails",
    difficulty: "Difficulty",
    any: "Any",
    easy: "Easy",
    moderate: "Moderate",
    hard: "Hard",
    distance: "Distance (km)",
    startHike: "Start Hike",
    download: "Download for Offline",
    addedFav: "Added to favorites",
    addFav: "Favorite",
    stats: "Stats",
    elevation: "Elevation",
    length: "Length",
    rating: "Rating",
    sso: "Single Sign-On",
    signIn: "Sign in with Google",
    signOut: "Sign out",
    biometrics: "Biometric Login",
    enable: "Enable",
    notifications: "Notifications",
    language: "Language",
    storage: "Storage Used",
    remove: "Remove",
    clearAll: "Clear All",
    offlinePacks: "Offline Packs",
  },
  af: {
    trails: "Roetes",
    details: "Besonderhede",
    map: "Kaart",
    downloads: "Aflaaie",
    profile: "Profiel",
    searchTrails: "Soek roetes",
    difficulty: "Moeilikheidsgraad",
    any: "Enige",
    easy: "Maklik",
    moderate: "Gemiddeld",
    hard: "Moeilik",
    distance: "Afstand (km)",
    startHike: "Begin Stap",
    download: "Laai af vir Vanlyn",
    addedFav: "By gunstelinge gevoeg",
    addFav: "Gunsteling",
    stats: "Statistiek",
    elevation: "Stygings",
    length: "Lengte",
    rating: "Gradering",
    sso: "Enkel Aanteken",
    signIn: "Meld aan met Google",
    signOut: "Meld af",
    biometrics: "Biometriese Teken-in",
    enable: "Skakel aan",
    notifications: "Kennisgewings",
    language: "Taal",
    storage: "Stoor gebruik",
    remove: "Verwyder",
    clearAll: "Vee Alles Uit",
    offlinePacks: "Vanlyn Pakkette",
  },
  zu: {
    trails: "Izindlela",
    details: "Imininingwane",
    map: "Imephu",
    downloads: "Okudayiwe",
    profile: "Iphrofayela",
    searchTrails: "Sesha izindlela",
    difficulty: "Ubunzima",
    any: "Noma yini",
    easy: "Kulula",
    moderate: "Maphakathi",
    hard: "Kunzima",
    distance: "Ibanga (km)",
    startHike: "Qala Ukuhamba",
    download: "Landa ukuze usebenze ngaphandle kwe-inthanethi",
    addedFav: "Kufakwe kokuthandwayo",
    addFav: "Okuthandwayo",
    stats: "Izibalo",
    elevation: "Ukuphakama",
    length: "Ubude",
    rating: "Isilinganiso",
    sso: "Ukungena okukodwa",
    signIn: "Ngena nge-Google",
    signOut: "Phuma",
    biometrics: "Ukungena ngebhayomethrikhi",
    enable: "Vula",
    notifications: "Izaziso",
    language: "Ulimi",
    storage: "Isitoreji esisetshenzisiwe",
    remove: "Susa",
    clearAll: "Sula Konke",
    offlinePacks: "Amaphakheji Angaxhunyiwe",
  },
};

export const MOCK_TRAILS = [
  {
    id: "mt-lion",
    name: "Mount Lion Ridge",
    city: "Magaliesberg, GP",
    lat: -25.792,
    lon: 27.946,
    distanceKm: 8.4,
    elevationM: 420,
    difficulty: "moderate",
    rating: 4.6,
    image:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop",
    tags: ["viewpoint", "waterfall"],
    downloaded: true,
  },
  {
    id: "cedar-loop",
    name: "Cedar Valley Loop",
    city: "Hennops, GP",
    lat: -25.886,
    lon: 27.983,
    distanceKm: 4.2,
    elevationM: 120,
    difficulty: "easy",
    rating: 4.2,
    image:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?q=80&w=1200&auto=format&fit=crop",
    tags: ["family", "picnic"],
    downloaded: false,
  },
  {
    id: "drakensberg-peak",
    name: "Drakensberg Peak Ascent",
    city: "KZN, SA",
    lat: -29.0,
    lon: 29.35,
    distanceKm: 14.7,
    elevationM: 980,
    difficulty: "hard",
    rating: 4.9,
    image:
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1200&auto=format&fit=crop",
    tags: ["alpine", "scramble"],
    downloaded: false,
  },
];

export const DIFFICULTY_ORDER = { any: 0, easy: 1, moderate: 2, hard: 3 };
export const tabs = { TRAILS: "TRAILS", DETAILS: "DETAILS", MAP: "MAP", DOWNLOADS: "DOWNLOADS", PROFILE: "PROFILE" };
