
import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  topbar: {
    height: 52,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0b1020",
  },
  brand: { color: "white", fontSize: 18, fontWeight: "800" },
  toplink: { color: "#94a3b8", fontSize: 12 },
  panel: {
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "#1f2937",
    borderRadius: 14,
    padding: 12,
    gap: 8,
  },
  panelTitle: { color: "white", fontWeight: "700", fontSize: 16 },
  input: {
    backgroundColor: "#0b1324",
    borderColor: "#1f2937",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "white",
  },
  label: { color: "#e2e8f0", fontSize: 12 },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#0b1324",
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  chipActive: { borderColor: "#22c55e", backgroundColor: "#0b1a2e" },
  chipText: { color: "#cbd5e1", fontSize: 12 },
  chipTextActive: { color: "#22c55e", fontWeight: "600" },
  card: {
    overflow: "hidden",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1f2937",
    backgroundColor: "#0f172a",
  },
  cardImage: { width: "100%", height: 150 },
  cardTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  cardTitle: { color: "white", fontWeight: "700", fontSize: 16, flex: 1, marginRight: 8 },
  cardSub: { color: "#94a3b8", marginLeft: 6, fontSize: 12 },
  cardMeta: { color: "#e2e8f0", fontSize: 12 },
  row: { flexDirection: "row", alignItems: "center", gap: 6 },
  badge: { borderRadius: 999, backgroundColor: "#0b1324", borderWidth: 1, borderColor: "#1f2937", paddingHorizontal: 8, paddingVertical: 3 },
  badgeText: { color: "#cbd5e1", fontSize: 11, textTransform: "capitalize" },
  smallBadge: { fontSize: 12, color: "#22c55e" },
  btnPrimary: { flexDirection: "row", gap: 6, backgroundColor: "#22c55e", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 },
  btnPrimaryText: { color: "white", fontWeight: "700" },
  btnSoft: { flexDirection: "row", gap: 6, backgroundColor: "#0b1324", borderWidth: 1, borderColor: "#1f2937", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 },
  btnSoftFull: { alignItems: "center", paddingVertical: 10, backgroundColor: "#0b1324", borderWidth: 1, borderColor: "#1f2937", borderRadius: 10 },
  btnSoftText: { color: "#e2e8f0", fontWeight: "600", fontSize: 12 },
  stat: { flexDirection: "row", alignItems: "center", gap: 8 },
  statLabel: { color: "#94a3b8", fontSize: 12 },
  statValue: { color: "#e2e8f0", fontWeight: "700" },
  segment: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#0b1324", borderWidth: 1, borderColor: "#1f2937", borderRadius: 10, padding: 10, marginTop: 8 },
  mapBox: { height: 300, borderRadius: 14, overflow: "hidden", backgroundColor: "#111827", borderWidth: 1, borderColor: "#1f2937" },
  mockGrid: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)" },
  mockPath: { position: "absolute", left: 20, right: 20, top: 140, height: 6, backgroundColor: "#059669", borderRadius: 999 },
  mockBadge: { position: "absolute", top: 10, left: 10, backgroundColor: "white", borderRadius: 10, paddingHorizontal: 8, paddingVertical: 6, flexDirection: "row", alignItems: "center" },
  downloadRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#0b1324", borderRadius: 12, borderWidth: 1, borderColor: "#1f2937", padding: 10 },
  progressOuter: { height: 10, backgroundColor: "#0b1324", borderRadius: 999, overflow: "hidden", borderWidth: 1, borderColor: "#1f2937" },
  progressInner: { height: 10, width: "40%", backgroundColor: "#22c55e" },
  avatar: { width: 34, height: 34, borderRadius: 999, backgroundColor: "#9ae6b4", alignItems: "center", justifyContent: "center" },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  tabs: { height: 62, borderTopWidth: 1, borderTopColor: "#1f2937", backgroundColor: "#0f172a", flexDirection: "row", justifyContent: "space-around", alignItems: "center" },
  tabBtn: { alignItems: "center", justifyContent: "center", gap: 2 },
  tabTxt: { color: "#94a3b8", fontSize: 11 },
  footer: { textAlign: "center", color: "#64748b", fontSize: 10, paddingBottom: 10 },
  tag: { paddingHorizontal: 8, paddingVertical: 4, backgroundColor: '#0b1324', borderRadius: 999, borderWidth: 1, borderColor: '#1f2937' },
  tagText: { color: '#93c5fd', fontSize: 11 },
});
